name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']

    name: PHP ${{ matrix.php }} tests

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: php Tests/fix_composer_json.php

      - uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--prefer-source"

      - run: vendor/bin/phpunit --exclude-group=functional
